spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/smartstudy}
spring.thymeleaf.cache=false

gemini.api.key=AIzaSyB3HGD_sT0k9W-zyHar77K7xIijUiZK4uI
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent
